DB_PASSWORD=root

MAIL_USERNAME=franklinsurya4@gmail.com
MAIL_PASSWORD=jowmnmgqrvvyasem

OPENAI_API_KEY=sk-proj-_D4RoX5L...

GOOGLE_CLIENT_ID=955042788179-xxxx.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=GOCSPX-xxxx

GITHUB_CLIENT_ID=Ov23liYzMpNqWb2BFcUX
GITHUB_CLIENT_SECRET=e4028bca7e771bfc9ff90f9ac45ea9fcee468ba6

SLACK_APP_ID=A0AHQ8H6269
SLACK_CLIENT_ID=10590200770727.10602289206213
SLACK_CLIENT_SECRET=19bd23499093e852f5c4909d276d81fe
SLACK_REDIRECT_URI=https://unsmooth-rosann-numerously.ngrok-free.dev/api/integrations/oauth/slack/callback
SLACK_SIGNING_SECRET=339e0ac1ee58553e1829eb9691e6b944

ENCRYPTION_KEY=1234567890123456
```

---

## `.gitignore` ? add these lines
```
application-local.properties
.env
.env.local