spring.application.name=TaskManagementTool
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/TaskMangementTool
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.aichatbot=DEBUG
logging.level.org.springframework.web=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS
cors.allowed-origins=http://localhost:3000

# AI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.ollama.chat.model=tinyllama:v0.6

# GOOGLE
google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}
google.redirect.uri=http://localhost:8080/api/integrations/oauth/google/callback

# GITHUB
github.client.id=${GITHUB_CLIENT_ID}
github.client.secret=${GITHUB_CLIENT_SECRET}
github.redirect.uri=http://localhost:8080/api/integrations/oauth/github/callback

# SLACK
slack.app.id=${SLACK_APP_ID}
slack.client.id=${SLACK_CLIENT_ID}
slack.client.secret=${SLACK_CLIENT_SECRET}
slack.redirect.uri=${SLACK_REDIRECT_URI}
slack.signing.secret=${SLACK_SIGNING_SECRET}

# ENCRYPTION KEY
app.encryption.key=${ENCRYPTION_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=uploads

spring.profiles.active=local